### ISSUE TITLE
Unable to change the font-size of bot message

### ISSUE THREAD

**Issue by yhranik-vp** [FlowiseAI/FlowiseChatEmbed#104]
When setting font-size for `chatWindow` element it affects all elements (title, user message, etc), except for the BOT message. 

See image attached.

```
      Chatbot.initFull({
        chatflowid: CHATBOT_CHATFLOWID,
        apiHost: CHATBOT_APIHOST,
        theme: {
          chatWindow: {
            showTitle: true,
            title: 'AI Assistant',
            height: 500,
            fontSize: 10 // <- does not affect bot message
          }
        }
      })
```
<img width="287" alt="Screenshot 2024-02-27 at 10 04 26" src="https://github.com/FlowiseAI/FlowiseChatEmbed/assets/150423082/70f19052-6ec3-4406-862c-938049247082">

**Comment by bgbbmm** [comment]
Can someone please review this linked PR and merge?

**Comment by HenryHengZJ** [comment]
should be resolved now
