### ISSUE TITLE
CSS Misconfiguration

### ISSUE THREAD

**Issue by toi500** [FlowiseAI/FlowiseChatEmbed#123]
There is a small css misconfiguration with the feedback box. Currency there is not margins when you use the Popup HTML script. (700x400px by default).

Now:

.mx-auto {
    margin-left: auto;
    margin-right: auto;
} 

It can be fixed by changing the left and right values to 20px or by injecting `.mx-auto {
  margin: 20px !important;
}` at the end of index.css

It will fit good with the Popup & Fullpage HTML scripts.

Result:

![Screenshot 2024-03-24 155257](https://github.com/FlowiseAI/FlowiseChatEmbed/assets/138339291/26f7654f-7e01-4663-8f27-ed1f8e99fac3)

**Comment by toi500** [comment]
Also, I think it would look better (a bit redundant IMO)  where the user can close without leaving a feedback by clicking outside the modal.

![Screenshot 2024-03-25 000032](https://github.com/FlowiseAI/FlowiseChatEmbed/assets/138339291/65cb105c-85bb-4e05-b6e7-90937a18a636)

**Comment by HenryHengZJ** [comment]
made some changes:
![image](https://github.com/FlowiseAI/FlowiseChatEmbed/assets/26460777/4b29ceef-c77f-4765-9144-24a425646dad)

hopefully this works better
