### ISSUE TITLE
The FullPageChat does not support multi-line input box by holding down the shift key.

### ISSUE THREAD

**Issue by nne998** [FlowiseAI/FlowiseChatEmbed#130]
The FullPageChat ( via shared link) does not support multi-line input when holding down the shift key; however, the popup one in editing mode can do this.

Thank you!

**Comment by HenryHengZJ** [comment]
should be supported now: 
![image](https://github.com/FlowiseAI/FlowiseChatEmbed/assets/26460777/7bbe94c0-296c-4150-bde7-af32cd0c965f)
