### ISSUE TITLE
Popup Mode misconfiguration

### ISSUE THREAD

**Issue by toi500** [FlowiseAI/FlowiseChatEmbed#132]
Right now, It makes no much sense to set up the position of the `button` since the `bot` (or chatWindows) does not follow and there is not an easy way to move it a round, no without touch the source code and cook a new web.js. 

--
<img width="528" alt="image" src="https://github.com/FlowiseAI/FlowiseChatEmbed/assets/138339291/afba5e77-80e3-44a5-965b-cab242bedf24">
--

And this because it renders as two independent elements in the body.

--
<img width="605" alt="image" src="https://github.com/FlowiseAI/FlowiseChatEmbed/assets/138339291/7ed8f41c-0152-4864-8ece-6ade19ed9cff">
--

Why do not we wrap them up so they can be moved together?

**Comment by amansoni7477030** [comment]
Hi @toi500, I've fixed this issue and added some latest functionality such as drag and drop, maxWords, and some more. Check out the new release of FlowiseChatEmbed. Now the chat window will follow along with the chat button. However, I'm still waiting for approval on the maxWords feature; it's in a pull request.

**Comment by amansoni7477030** [comment]
Thank you @toi500. I have already made some enhancements to the embedded chat. It is still in testing, but I will push it soon. It will also be responsive on mobile.

**Comment by toi500** [comment]
You are the man, @amansoni7477030 . Thank you so much for take care of this.

Maybe you have already noticed but, on mobile, there is a "auto-focus" (1) when you open the embedded chat and (2) when you get a response from the model, resulting the end user has just a little windows to read and a very bad user experience, since you need to keep pressing "back" on the phone to get rip of the mobile keyboard and be able to read.

https://github.com/FlowiseAI/FlowiseChatEmbed/assets/138339291/d830e50b-8c91-461b-8406-93ba6387dc72

For a really smoth user experience, here is how it should work, without any autofocus.

https://github.com/FlowiseAI/FlowiseChatEmbed/assets/138339291/b91a57c2-fcb3-44e0-ac29-b2d5197d8fc5

CC: @HenryHengZJ

**Comment by amansoni7477030** [comment]
@toi500 I get it i will also include this point in my code so it will work as you mentioned.

**Comment by amansoni7477030** [comment]
Hi @toi500, please check #183 . Wait for it to be approved. Now it will be very responsive on any platform. I made changes in many files and also added the close button at the top of the chat window. Now it will work very responsively.

**Comment by NicolasGramnea** [comment]
@amansoni7477030 I believe some of the changes affected the chatWindow view on mobile devices. It's offset (right) is not working properly. It goes outside the screen... hiding the reset / new chat button.

**Comment by amansoni7477030** [comment]
Hi @NicolasGramnea ,
I’ve identified the issue with the chat window view on mobile devices. I’ve made the necessary changes in my repository, and I’m waiting for my latest pull request #183  to be approved. This update will solve all the responsiveness issues on any device and ensure everything works perfectly.
