### ISSUE TITLE
Embedding the flowise chat-bot with default nginx index.html caused CORS issue.

### ISSUE THREAD

**Issue by quzhixue-Kimi** [FlowiseAI/FlowiseChatEmbed#169]
hi there,

I just test the flowise chat-bot with defaul nginx index.html page with following steps:

1. There has been a flowise flow with host like 'aiflowise.kq.eu.org'
<img width="864" alt="Screenshot 2024-05-24 at 14 51 39" src="https://github.com/FlowiseAI/FlowiseChatEmbed/assets/8235746/7d34dac9-9334-46b6-9a25-6e2eaed77a7a">

2. There has been another default nginx index.html page with host like 'abc-18688.xyz'. 

Following the code as doc showing to insert below code into the default index.html.
<script type="module">
    import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js"
    Chatbot.init({
        chatflowid: "b8f72c44-1502-4c86-bc96-ef799660a4d1",
        apiHost: "https://aiflowise.kq.eu.org",
    })
</script>

4. Reload the nginx process, and the chat-bot has been displayed. 
But, the page got the issue 

Access to fetch at 'https://aiflowise.kq.eu.org/api/v1/chatflows-streaming/b8f72c44-1502-4c86-bc96-ef799660a4d1' from origin 'https://abc-18688.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

'Access to XMLHttpRequest at 'https://aiflowise.kq.eu.org/socket.io/?EIO=4&transport=polling&t=O-fPO6P' from origin 'https://abc-18688.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.'

Is there any configuration that I missed?

The nginx.conf configued with these headers

location / {
		add_header 'Access-Control-Allow-Origin' '*';
    		add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    		add_header 'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
    		add_header 'Access-Control-Expose-Headers' 'Content-length, Content-Range';
		root	/var/www/html;
		index index.html;
	}

Any suggestion or feedback is appreciated.

BR

Kimi

**Comment by HenryHengZJ** [comment]
You'll have to specify env variables in your `.env` file - https://docs.flowiseai.com/using-flowise/embed#cors

**Comment by quzhixue-Kimi** [comment]
Hi there,

Thank you for your helpful information.

Issue has been fixed based on the document.

BR
Kimi
