### ISSUE TITLE
chatWindow goes outside (right) on mobile devices

### ISSUE THREAD

**Issue by NicolasGramnea** [FlowiseAI/FlowiseChatEmbed#187]
The chat window is not centered on mobile devices. It goes outside of the screen (right side)

Making it hard to read + the reset chat button is no longer visible.
![16_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/FlowiseAI/FlowiseChatEmbed/assets/79979014/56149a18-9e1a-4863-b790-e66e83cd2f6b)

**Comment by amansoni7477030** [comment]
Hi @NicolasGramnea ,
I’ve identified the issue with the chat window view on mobile devices. I’ve made the necessary changes in my repository, and I’m waiting for my latest pull request #183  to be approved. This update will solve all the responsiveness issues on any device and ensure everything works perfectly.

**Comment by HenryHengZJ** [comment]
with @amansoni7477030's PR, this should be fixed, Released in 1.3.3, thanks @amansoni7477030 !
