### ISSUE TITLE
[BUG] Agentflows only shows last worker message and no others when using "FlowiseChatEmbed"

### ISSUE THREAD

**Issue by LuisFX** [FlowiseAI/FlowiseChatEmbed#204]
Describe the bug
As per the title, when using share chatbot no agentflow messages appear except for the very last one on Finish. No supervisor or any other workers messages are displayed.

To Reproduce

Go to '.Share Chatbot"
Click on '.Send Message'
Scroll down to '.N/A'
See error
Expected behavior
To show the sequence of messages from Supervisor through workers

Setup

Installation [Docker]
Flowise Version [1.8.3]
OS: [Win 11]
Browser [Chrome]

Refer to same issue fixed in "Share Bot"
https://github.com/FlowiseAI/Flowise/issues/2746

**Comment by HenryHengZJ** [comment]
pushed a fix here - https://github.com/FlowiseAI/Flowise/pull/2749

will be resolved if you update your fork to latest. otherwise, we have to wait until next release
