### ISSUE TITLE
How to make the chat embed responsive?

### ISSUE THREAD

**Issue by donvito** [FlowiseAI/FlowiseChatEmbed#5]
I am embedding the chat module but it seems that the chat window is not responsive in mobile. I am using the custom config as suggested. Any ideas how to make the chat window responsive?

**Comment by HenryHengZJ** [comment]
do you have a screenshot when used in mobile where its not responsive?

**Comment by HenryHengZJ** [comment]
https://github.com/FlowiseAI/FlowiseChatEmbed/pull/6 should fixed this
