### ISSUE TITLE
401 Unauthorized /api/v1/public-chatbotConfig/ac8240fc...

### ISSUE THREAD

**Issue by azzuwayed** [FlowiseAI/FlowiseChatEmbed#68]
Hello,

This issue could be related to circumstances outside of flowsieai, such as Cloudflare or Nginx Proxy Manager.
I have successfully deployed the chatbot with GPT4 integration and everything is working without any issues.
Every resource is loading without issues. There's just one file per the screenshot that is failing to load due to "unauthorized access" /api/v1/public-chatbotConfig/ac8240fc...

Your support is highly appreciated.

![Screenshot 2023-12-17 155957](https://github.com/FlowiseAI/FlowiseChatEmbed/assets/143247600/170ec934-3d52-4940-b5e4-3d99186fac38)

**Comment by HenryHengZJ** [comment]
you'll have to upgrade your flowise main app version

**Comment by nbyte123** [comment]
Hello.
I have the same problem. What should I do?

**Comment by HenryHengZJ** [comment]
Make sure you have the latest Flowise version installed, issue should be resolved with this [PR](https://github.com/FlowiseAI/Flowise/pull/1500)
