### ISSUE TITLE
After refreshing the page, the user's chat history is lost

### ISSUE THREAD

**Issue by hisune** [FlowiseAI/FlowiseChatEmbed#7]
After refreshing the page, the user's chat history is lost
Is it possible to save the recent chat history even after refreshing the page? Similar effect in chatflows admin backend

**Comment by qicdvp** [comment]
@hisune Were you able to find a solution for this?
I have deployed the instance in Azure. But when refreshed my workflow is getting erased as well in dashboard.

**Comment by kad3nce** [comment]
I came here with the same need. I found this (apparently) WIP branch to add this. No idea if it's functional: https://github.com/FlowiseAI/FlowiseChatEmbed/commits/feature/ChatHistory

**Comment by hisune** [comment]
> @hisune Were you able to find a solution for this? I have deployed the instance in Azure. But when refreshed my workflow is getting erased as well in dashboard.

@qicdvp @kad3nce 
I wrote my own program and have been using it on my site for a while now and it's perfect: [https:github.com/hisune/chatgpt-widget](https:github.com/hisune/chatgpt-widget)
