### ISSUE TITLE
 Font size of the botMessage 

### ISSUE THREAD

**Issue by omnipro-bh** [FlowiseAI/FlowiseChatEmbed#81]
Hi Team, 

As the attached screenshot.  appears that the font size of the botMessage is indeed smaller than the userMessage, although i have added the Embed Chat Config, and when i change the font size it reflect on userMessage only, and botMessage is stays the same. 

very strange issue, anyone faced this before ?

Appreciate if someone can assist. 
<img width="225" alt="Screenshotwe" src="https://github.com/FlowiseAI/FlowiseChatEmbed/assets/143381088/70f5e64a-03ad-4f4e-ac6e-6c29b2da6b8c">

**Comment by omnipro-bh** [comment]
when I use the regular/original code, it seems fine without any issue.. as the screenshot attached.. only when i use the FlowiseChatEmbed, the botMessage font stays smaller than userMessage. 

if anyone faced this or have any clue ??

<img width="210" alt="Orgcode" src="https://github.com/FlowiseAI/FlowiseChatEmbed/assets/143381088/f2646018-0818-48f1-8e9f-6925e6468fad">

**Comment by sirsimonson** [comment]
![image](https://github.com/FlowiseAI/FlowiseChatEmbed/assets/42245157/5418e33f-39de-43a1-92ce-84eb27a155ad)
This fixed it for me. I haven't checked what prose from tailwind really does but now it'a applied properly. Any concerns?

**Comment by omnipro-bh** [comment]
> ![image](https://private-user-images.githubusercontent.com/42245157/305181908-5418e33f-39de-43a1-92ce-84eb27a155ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNjAxODUsIm5iZiI6MTcwODE1OTg4NSwicGF0aCI6Ii80MjI0NTE1Ny8zMDUxODE5MDgtNTQxOGUzM2YtMzlkZS00M2ExLTkyY2UtODRlYjI3YTE1NWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA4NTEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ODYzZDQ1YTdhZTcyZTcwNzQ3MTRmM2M4YWM5ZmZiOTQwYTY3MGU0NTE2YjQ5ODlmMzE0NGVmNDM1NDc3NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jm0KhuPdLSNyg07bxHO6gGtD0KKyr90BPSsRczANp7M) This fixed it for me. I haven't checked what prose from tailwind really does but now it'a applied properly. Any concerns?

Thank you for your replay, in which file this code exist ? i couldn't find it

**Comment by omnipro-bh** [comment]
I have found the file its under /tree/main/src/components/bubbles/BotBubble.tsx 

changes is done and removed "prose", Commit the code and push it. but still the same for me the botMessage font stays smaller than userMessage.

**Comment by omnipro-bh** [comment]
Hi dear, it works fine. Please pin this as solution for whoever facing similar issue. 

thanks

**Comment by bgbbmm** [comment]
@HenryHengZJ I saw your PR merged to fix the font size property yesterday. I am using the npm packages flowise-embed and flowise-embed-react. I believe an updated package for flowise-embed would need to be made to incorporate your fix, and that it resolves this issue. Is that true? When will a new package be made available?

Thanks
