### ISSUE TITLE
Chatbot Button Size

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/FlowiseChatEmbed#85]
Ability to set chatbot button size via `px`?
The sizes "small", "medium" and "large" are not sufficient

https://github.com/FlowiseAI/Flowise/discussions/1546

**Comment by amansoni7477030** [comment]
Hii @HenryHengZJ  I added functionality in my latest pull request that allows users to customize the chatbot button size. I also included some other features. Can you please verify my pull request?

**Comment by amansoni7477030** [comment]
i also added other enhancement in that pull request.
