### ISSUE TITLE
Is there a method to modify or conceal the 'powered by' text?

### ISSUE THREAD

**Issue by joelket23** [FlowiseAI/FlowiseChatEmbed#93]
<img width="433" alt="Screenshot 2024-02-12 at 15 49 34" src="https://github.com/FlowiseAI/FlowiseChatEmbed/assets/82398173/4a23b715-cee4-4190-acb7-895060b87e2d">

**Comment by chungyau97** [comment]
https://docs.flowiseai.com/using-flowise/embed
